name: Challenge 20 CICD Render

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  render-deploy:
    runs-on: unbuntu-latest
    strategy:
    matrix:
      node-verions: [18.x, 20.x, 22.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CI and CD using Node 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install dependencies
      run: npm ci

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
